{
 "title": "TM",
 "time": { "from": "2025-03-26T08:02:20.817Z", "to": "2025-03-26T08:45:51.057Z" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum((rate(node_cpu_seconds_total[1m]))) by (cpu) / 12",
     "legendFormat": "{{cpu}}"
    },
    {
     "expr": "sum((rate(node_cpu_seconds_total[1m]))) by (device) / 12",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / 1024 / 1024 / 1024",
     "legendFormat": "Installed"
    },
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024 / 1024",
     "legendFormat": "Used"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "Swapped"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])) by(device)",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!=\"lo\"}[1m])) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available Disk Storage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{device!=\"tmpfs\", device!=\"gvfsd-fuse\"} / 1024 / 1024 / 1024) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Free Disc Space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{device!=\"tmpfs\", device!=\"gvfsd-fuse\"}) by (device) / sum(node_filesystem_size_bytes{device!=\"tmpfs\", device!=\"gvfsd-fuse\"}) by (device) * 100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Read Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Write Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}