version: '3'
services:
  backend:
    build:
      context: ..
      dockerfile: serving/backend/Dockerfile
    ports:
      - "8000:8000"

  streamlit:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend